### ISSUE TITLE
make Go template that when passed a path can construct the rest of a dagger workflow for github actions.

### ISSUE THREAD

**Issue by TimothyStiles** [TimothyStiles/buster#17]
```yaml

name: status check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dagger-status-check:
    name: Dagger runtime status check
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Dagger
        run: go get dagger.io/dagger@latest
      - name: Install Dagger
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
      - name: Run Dagger workflow
        run: dagger run go run {path-to-workflow-here}
```
